### ISSUE TITLE
[Bug]: Sophisticated Storage Quest Tasks (Normal)

### ISSUE THREAD

**Issue by hk21702** [ThePansmith/Monifactory#530] opened 2024-08-15 12:02 UTC
### Issue Summary

Two things about this quest. Currently, the task is for a "Oak Iron Barrel" which can't be crafted. You can make a spruce iron barrel, and that completes the task. However, you can't click on item in the task to view the recipe (since you can't make the oak iron barrel).

Additionally, the any sophisticated backpack task should ideally include other backpack versions like the "Upgraded Backpack". Especially as some of these variants like the "Upgraded Backpack" can show in in loot chests in lost cities. 

### Reproduction steps

Try clicking on the "oak iron barrel" in the questbook and nothing happens.

Have an "upgraded backpack" in your inventory, and the task does not complete.

**Comment by glektarssza** [comment] 2024-08-19 13:31
The Oak Iron Barrel can be crafted. I have four of them in my private server world right now. The recipe is currently:

```
III
BBB
III
```
where

* `I` = `minecraft:iron_ingot`
* `B` = `minecraft:barrel`

If the recipe is not showing in EMI that may be an EMI bug. It shows for me right now but I will double check when I get off work today to confirm.

**Comment by hk21702** [comment] 2024-08-19 13:38
![image](https://github.com/user-attachments/assets/4d4e2e9e-45e8-46e2-b738-4c739d2b6d95)
The recipe results in a spruce iron barrel for me. 

EMI only shows a recipe for the spruce iron barrel. Nothing for oak iron barrel.

**Comment by glektarssza** [comment] 2024-08-19 14:03
Weird. I distinctly recall it showing as an Oak Iron Barrel for me. Like I said, I will double check everything when I get off work today.

**Comment by glektarssza** [comment] 2024-08-23 13:15
Okay, doubled checked it this morning before work. Sorry for the delay.

I can confirm that the Oak Iron Barrel does, indeed, not show up in EMI despite being the item required for the quest. The Spruce Iron Barrel does but crafting that recipe produces an Oak Iron Barrel for me which completes the quest. Very strange behavior and definitely confusing.

I'll probably poke around the KubeJS scripts this weekend and try to track down what's going on.

**Comment by glektarssza** [comment] 2024-08-23 14:36
Looks like this was purposefully changed in d9c2d5d as part of #509. The correct fix for this issue is to update the quest. I will create a PR for this.

**Comment by glektarssza** [comment] 2024-08-23 14:53
Down the road this quest should probably be updated to accept "Any Sophisticated Storage Barrel" once the other barrels are added back in (as per the rest of the commit message in d9c2d5d).

**Closed** 2024-09-21 18:38 UTC
Labels: bug
