### ISSUE TITLE
[Bug]: Effortless Building Muscles Dupe

### ISSUE THREAD

**Issue by ThePinkPotato** [ThePansmith/Monifactory#682] opened 2024-09-10 01:25 UTC
### Issue Summary

The muscles from the effortless building mod get duplicated.

### Reproduction steps

Open chest with muscles in it.
Take muscles out
Right click to use 
open chest again - muscles should appear in hotbar
Repeat

**Comment by ThePinkPotato** [comment] 2024-09-10 01:26
Might only work for lootr chests. my minecraft crashed before i could try

**Comment by Yokoharu** [comment] 2024-09-10 08:04
Duplicate of #514. Known issue with the mod itself.

**Closed** 2024-09-10 16:56 UTC
Labels: bug
