### ISSUE TITLE
[Feature]: upgrade to 1.20.4 or later to fix AE2/EMI integration

### ISSUE THREAD

**Issue by Spongman** [ThePansmith/Monifactory#949] opened 2024-10-16 06:40 UTC
### Suggestion

AE2 doesn't integrate with EMI until the 1.20.4 release.

**Comment by MightyPiggie** [comment] 2024-10-16 10:59
I doubt this modpack will ever update to 1.20.4 since every mod needs to be updated.

**Comment by Kasra-G** [comment] 2024-10-19 04:29
Can we add this mod then?
https://www.curseforge.com/minecraft/mc-mods/ae2-emi-crafting-integration

**Comment by jhagrid77** [comment] 2024-10-19 04:39
Would actually need all of the following mods for that integration to work (have it in my own instance):
- https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api
  - Fabric API to Forge
- https://www.curseforge.com/minecraft/mc-mods/sinytra-connector
  - Compatibility layer for Fabric -> Forge
- https://www.curseforge.com/minecraft/mc-mods/connector-extras
  - Needed for the EMI integration from the Fabric mod to actually function
- https://www.curseforge.com/minecraft/mc-mods/ae2-emi-crafting-integration
  - This is a Fabric mod
- https://www.curseforge.com/minecraft/mc-mods/modmenu
  - Needed for any folks that want to allow EMI to read their ME system
    - I like this to be able to continue to use the recipe tree crafting needs within my ME system

**Comment by Kasra-G** [comment] 2024-10-19 05:11
> Would actually need all of the following mods for that integration to work (have it in my own instance):
> 
> * https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api
>   
>   * Fabric API to Forge
> * https://www.curseforge.com/minecraft/mc-mods/sinytra-connector
>   
>   * Compatibility layer for Fabric -> Forge
> * https://www.curseforge.com/minecraft/mc-mods/connector-extras
>   
>   * Needed for the EMI integration from the Fabric mod to actually function
> * https://www.curseforge.com/minecraft/mc-mods/ae2-emi-crafting-integration
>   
>   * This is a Fabric mod
> * https://www.curseforge.com/minecraft/mc-mods/modmenu
>   
>   * Needed for any folks that want to allow EMI to read their ME system
>     
>     * I like this to be able to continue to use the recipe tree crafting needs within my ME system

Thanks for the suggestion, though wasn't able to get the recipe tree integration working on my end.

I went ahead and just +1'd this request for a forge 1.20.1 backport on the ae2-emi crafting integration fabric mod

https://github.com/blocovermelho/ae2-emi-crafting/issues/5

**Comment by piersh-aetheros** [comment] 2024-10-19 06:08
Yeah, I have actually stopped playing Monifactory because of this.

Once I found out that moving to AE2 breaks the EMI crafting tree, I suddenly lost interest.

**Comment by Spongman** [comment] 2024-10-19 06:10
Yeah, I have actually stopped playing Monifactory because of this.

Once I found out that moving to AE2 breaks the EMI crafting tree, I suddenly lost interest.

**Comment by Spongman** [comment] 2024-10-19 19:57
it doesn't really work either. when you're in the AE2 terminal, the EMI synthetic favorites doesn't 'see' the items in the AE2 storage. it doesn't even 'see' the items in the player's inventory, either.

here, i have 2 Flux Coils in my inventory, and EMI says it needs 4 more.

![image](https://github.com/user-attachments/assets/9739777e-f193-47ba-9308-223b5f3ca42d)

however, if i open the AE terminal, EMI shows it now needs 6 more, even though i still have those 2 in my player inventory.

![image](https://github.com/user-attachments/assets/7ec1876f-6972-4098-a765-b02384f6d342)

**Comment by MightyPiggie** [comment] 2024-10-19 19:59
Mmmh weird. For me it worked. Did you enable to option for the crafting integration? It's disabled by default

**Comment by jeytee84** [comment] 2024-10-20 22:50
Just tested it, it totally works! Here's the process in a bit more detail:

1. Download the first 3 in CurseForge launcher (just copy their name into the search and add them)
Forgified Fabric API
Sinytra Connector
Connector Extras

2. Download these from curseforge.com manually (because you can't form the launcher), and drop them into your mods folder:
https://www.curseforge.com/minecraft/mc-mods/ae2-emi-crafting-integration/files/all?page=1&pageSize=20&version=1.20.1
https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all?page=1&pageSize=20&version=1.21

3. Once ingame, hit escape, mod menu

The exact versions confirmed working on Monifactory 0.9.10:
modmenu-7.2.2
ae2-emi-crafting-1.3.1
ConnectorExtras-1.11.2+1.20.1
Connector-1.0.0-beta.46+1.20.1
fabric-api-0.92.2+1.11.8+1.20.1

Thank you guys for the tip! EMI's BoM feature absolutely spoiled me, I feel like I can't play without it. Now I can continue my playthrough! Cheers!

**Comment by Kasra-G** [comment] 2024-10-22 04:13
> The exact versions confirmed working on Monifactory 0.9.10: 
> fabric-api-0.92.2+1.11.8+1.20.1 
> Connector-1.0.0-beta.46+1.20.1 
> ConnectorExtras-1.11.2+1.20.1 
> ae2-emi-crafting-1.3.1 
> modmenu-7.2.2

This was really useful. Finally got it to work because after realizing I had installed the wrong connector mod

**Comment by WithersChat** [comment] 2024-10-27 09:17
Updating the entire pack to 1.20.4 is impossible, since GTm doesn't exist on that version.

Sinytra connector is way too unreliable for this to be added to the pack as is (We literally did all we could to **avoid** using it a few months back). Gonna bring up the issue to the dev team tho.

**Comment by jeytee84** [comment] 2024-10-27 10:27
Since the pack (questbook) highlights the BoM feature really strong, (this was what made me uset it for the first time ever), I think something definitelly should be done to improve its integration.

I think there are a few things that could be done:
- **Mention in the questbook** (either at the Crafting terminal or Recipe trees section (or both)) that AE2 integration is not yet complete and you should rely on Sophisticated storage barrels and maybe a Storage controller even to use with the crafting station until you reach HV and get access to ME Patterns and autocrafting.
- **Mention in the Addon Mods section** that AE2/EMI compatibility is possible via Connector and link maybe [my comment](https://github.com/ThePansmith/Monifactory/issues/949#issuecomment-2425270999) or create a new thread to show and let players track compatibility.
- **Wait for AE2 support**, I doubt there's going to be anything soon, but it could be happening. [The mentioned performance](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8214) issues are not gamebreaking, but do exist, but I dont thing it would become a big problem for anyone until late HV where the feature is already pretty much obsolete anyway so can be toggled off.

Losing this feature right in the beginning of a playthrough when you should be rewarded and relieved that you got your ME system up and running is a bummer, but could be totally mitigated as mentioned above, and it definitelly makes LV-MV more playable.

**Comment by ThePansmith** [comment] 2024-10-29 20:31
Porting the modpack isnt a viable option, you would have better luck trying to get those features backported.

**Closed by ThePansmith** 2024-10-29 20:31 UTC

**Comment by talchas2** [comment] 2025-01-15 09:51
The ae2-emi-crafting mod basically doesn't need fabric at all, the only fabric-specific behavior is the config loader/menu and "which ae2 mods are loaded" for optional deps on the wireless terminal. [This](https://gitlab.com/talchas/ae2-emi-crafting-forge) is a halfassed forge port of the mod which just hardcodes bomsync=true, alwayssync=false and requires ae2wtlib.

**Comment by dandy-is-lion** [comment] 2025-03-18 09:31
> The ae2-emi-crafting mod basically doesn't need fabric at all, the only fabric-specific behavior is the config loader/menu and "which ae2 mods are loaded" for optional deps on the wireless terminal. [This](https://gitlab.com/talchas/ae2-emi-crafting-forge) is a halfassed forge port of the mod which just hardcodes bomsync=true, alwayssync=false and requires ae2wtlib.

The only trouble I have with this port is that the Craftables shows everything you can do with an item, not just in a crafting grid. Really nice port though!

![Image](https://github.com/user-attachments/assets/235d5bb9-0e88-4221-89bd-b5df4334378d)

**Comment by ICantRanch** [comment] 2025-06-21 04:33
Are you guys able to get craft to inventory working? I can get the BoM working fine but craft to inventory only fills the grid. I still need to take each craft out manually
