### ISSUE TITLE
[Feature]:add the server to curseforge

### ISSUE THREAD

**Issue by yakla** [ThePansmith/Monifactory#824] opened 2024-10-01 06:45 UTC
### Suggestion

most server providers don't let you access to their files of the servers and you need to request a modpack from a external sorce like curseforge can you please add the server file to forge and with that it will be easyer to get a server of monifactory hosted ?

**Comment by ThePansmith** [comment] 2024-10-11 20:23
Dupe of #490

**Closed by ThePansmith** 2024-10-11 20:23 UTC
