### ISSUE TITLE
[Bug]: Friend cant connect to lan game

### ISSUE THREAD

**Issue by adamlolgaming** [ThePansmith/Monifactory#936] opened 2024-10-14 17:44 UTC
### Issue Summary

We both updated our 0.9.5 prism instances to the newest version and my friend cant connect to my LAN game
![image](https://github.com/user-attachments/assets/a6b9e843-f069-4c2c-b2d4-e96393ab4fbb)
resulting error 

### Reproduction steps

1. start LAN world
2. join the world 
3. uh oh spooky error!

### Relevant log output

```shell
[19:42:35] [User Authenticator #3/INFO] [minecraft/ServerLoginPacketListenerImpl]: UUID of player PLBartoszPL is 5a459798-88a4-4ed5-a8c6-486d4f402b40
[19:42:38] [Server thread/INFO] [minecraft/PlayerList]: PLBartoszPL[/[ip of player]] logged in with entity id 623 at (-592.7706225654816, 95.0, -375.17260015862604)
[19:42:38] [Server thread/INFO] [minecraft/MinecraftServer]: PLBartoszPL joined the game
[19:42:38] [Render thread/INFO] [minecraft/ChatComponent]: [CHAT] PLBartoszPL joined the game
[19:42:38] [Netty Server IO #5/ERROR] [Essential Logger/]: Network Exception Caught
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.gregtechceu.gtceu.api.recipe.ingredient.FluidContainerIngredient@6c7e2c8a
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at net.minecraft.network.Connection.m_243087_(Connection.java:224) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:213) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar%23121!/:4.1.82.Final] {}
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final] {}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin}
Caused by: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.gregtechceu.gtceu.api.recipe.ingredient.FluidContainerIngredient@6c7e2c8a
	at net.minecraft.world.item.crafting.Ingredient.getSerializer(Ingredient.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:zeta_forge.mixins.json:IngredientMixin,pl:mixin:APP:kubejs-common.mixins.json:IngredientMixin,pl:mixin:APP:gtceu.mixins.json:IngredientAccessor,pl:mixin:APP:kubejs_enderio.mixins.json:IngredientAccessor,pl:mixin:A}
	at net.minecraftforge.common.crafting.CraftingHelper.write(CraftingHelper.java:78) ~[forge-1.20.1-47.3.7-universal.jar%23561!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.item.crafting.Ingredient.m_43923_(Ingredient.java:99) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:zeta_forge.mixins.json:IngredientMixin,pl:mixin:APP:kubejs-common.mixins.json:IngredientMixin,pl:mixin:APP:gtceu.mixins.json:IngredientAccessor,pl:mixin:APP:kubejs_enderio.mixins.json:IngredientAccessor,pl:mixin:A}
	at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6178_(ShapedRecipe.java:339) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:classloading}
	at net.minecraft.world.item.crafting.ShapedRecipe$Serializer.m_6178_(ShapedRecipe.java:301) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_179469_(ClientboundUpdateRecipesPacket.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:classloading}
	at net.minecraft.network.FriendlyByteBuf.m_236828_(FriendlyByteBuf.java:221) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_5779_(ClientboundUpdateRecipesPacket.java:27) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:classloading}
	at net.minecraftforge.network.filters.VanillaPacketSplitter.appendPackets(VanillaPacketSplitter.java:66) ~[forge-1.20.1-47.3.7-universal.jar%23561!/:?] {re:classloading}
	at net.minecraftforge.network.filters.ForgeConnectionNetworkFilter.splitPacket(ForgeConnectionNetworkFilter.java:62) ~[forge-1.20.1-47.3.7-universal.jar%23561!/:?] {re:classloading}
	at net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:60) ~[forge-1.20.1-47.3.7-universal.jar%23561!/:?] {re:classloading}
	at net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:23) ~[forge-1.20.1-47.3.7-universal.jar%23561!/:?] {re:classloading}
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final] {}
	... 16 more
[19:42:38] [Server thread/INFO] [or.ze.so.SolarFlux/]: Sending solar panels to PLBartoszPL.
[19:42:38] [Server thread/INFO] [Jade/]: Syncing config to PLBartoszPL (5a459798-88a4-4ed5-a8c6-486d4f402b40)
[19:42:38] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: PLBartoszPL lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Modders must implement Ingredient.getSerializer in their custom Ingredients: com.gregtechceu.gtceu.api.recipe.ingredient.FluidContainerIngredient@6c7e2c8a
[19:42:38] [Server thread/INFO] [minecraft/MinecraftServer]: PLBartoszPL left the game
[19:42:38] [Render thread/INFO] [minecraft/ChatComponent]: [CHAT] PLBartoszPL left the game
```

**Comment by Krisz9000** [comment] 2024-10-14 18:56
Duplicate of: #929 ,thread has the solution as well

**Closed** 2024-10-14 19:05 UTC
Labels: bug
