### ISSUE TITLE
[Bug]: Conveyor module not working on MV Macerator.

### ISSUE THREAD

**Issue by lbkaehr** [ThePansmith/Monifactory#1131] opened 2024-11-16 04:18 UTC
### Issue Summary

Using a ULV/LV conveyor module on a MV Macerator doesn't allow for imports into the machine from a barrel and / or barrel.

### Reproduction steps

Place a MV Compressor down, barrel on top, set output to barrel
Place a MV Macerator to the left of the barrel. 
Add ULV or LV conveyor module to the right side of the Macerator.
using a screwdriver set to import.
nothing happens.

(I'm trying to compress sugarcane into plant balls and macerate them into bio chaff)
(This is only an issue on 10.1, It works on 10.0)

**Comment by jellonek** [comment] 2024-11-17 13:34
The issue is that changing the direction on conveyor belt fails to happen. If you will change it to import, then reenter gui - it will again show export.
Conveyors which were placed/configured in 0.10.0 still work, so it looks like issue with ownership of a cover.

Hopefully fixed in 0.10.2. May be releated to https://github.com/ThePansmith/Monifactory/pull/1130/files#diff-b93c652b684694997137cb5123a98ca2c33eb4b119bfdd76f810c52ec887a0dbL262 where i can see some changes in that direction.

**Comment by ThePansmith** [comment] 2024-11-23 17:05
Report to applicable mod devs

**Closed by ThePansmith** 2024-11-23 17:05 UTC
Labels: bug
